### ISSUE TITLE
I wonder if Potion Core's Damage Resist Attribute...

### ISSUE THREAD

**Issue by Z-Tunic** [Meldexun/RLTweaker#4]
Since this this mod has some Potion Core related things and the RLTweaker is a bugfix / performance. I wonder if Potion Core's Damage Resist Attribute can be fixed as it conflicts with Vanilla Damage Resist in a way. Here's a comment that I posted on Potion Core's curseforge page listing the details.

(Quote)
>Potion Core's Resist has a conflict with Vanilla Resist if it's default value was changed by... say... Potion Tweaker. It's a mod that allows you to change the default values that potions give for strength potions, weakness potions, instant damage potions, etc.

>Here's a breakdown between No Potion Core & Potion Core. With Potion Tweaker I changed the resist value from 0.2 (20%) to 0.1 (10%).
```
(0)R0= 1001 1001 1001 1001 | 0%
(-)R1= ____ 0901 ____ 0901 | 10%
(1)R2= 0801 0801 0801 0801 | 20%
(-)R3= ____ 0701 ____ 0701 | 30%
(2)R4= 0601 0601 0601 0601 | 40%
(-)R5= ____ 0501 ____ 0501 | 50%
(3)R6= 0400 0400 0400 0480 | 60%
(-)R7= ____ 0300 ____ 0420 | 70%
(4)R8= 0200 0200 0200 0320 | 80%
(-)R9= ____ 0100 ____ 0180 | 90%
(T)RT= 0000 0000 0000 0000 |100%

===========================
Resist 0.2 0.1 0.2PC 0.1PC
```
>This has been looked into and this is due to the Resist in Potion Core being hard coded with 0.2D (20%) so it will always expect that level 5 is the max. If it goes above level 5, then the damage reduction ends up breaking.

>One other bug occurs where if you have Vanilla Resist & Potion Core Resist attributes... you CANNOT have both at the same time if they reach high values otherwise the damage reduction will get a bit messy. Example...

>Zombie Pigman hits me for 12 Damage with no resistance of any kind on World Difficulty Hard.

>Resistance I (+20%) = 10 Damage Taken.
Resistance II (+40%) = 7 Damage Taken.
Resistance III (+60%) = 5 Damage Taken.
Resistance IV (+80%) = 2 Damage Taken.

>+50% Potion Core Resist = 6 Damage Taken.
+100% Potion Core Resist = 0 Damage Taken.

>I am now gonna add in scaling health but without any damage scaling, as it has a debug option to show your exact health value. This is what I get with both Resistances. Note that this can happen without scaling health being used.

>+50% Potion Core Resistance + Resistance I (+20%) = 4 Damage Taken. (16.16 / 20.0 Health)
+50% Potion Core Resistance + Resistance II (+40%) = 3 Damage Taken. (17.119999 / 20 Health)
+50% Potion Core Resistance + Resistance III (+60%) = 3 Damage Taken. (17.119999 / 20 Health)
+50% Potion Core Resistance + Resistance IV (+80%) = 2 Damage Taken. (18.08 / 20.0 Health)

>+100% Potion Core Resistance + Resistance I (+20%) = 2 Damage Taken. (18.08 / 20.0 Health)
+100% Potion Core Resistance + Resistance II (+40%) = 3 Damage Taken. (17.119999 / 20 Health)
+100% Potion Core Resistance + Resistance III (+60%) = 3 Damage Taken. (17.119999 / 20 Health)
+100% Potion Core Resistance + Resistance IV (+80%) = 2 Damage Taken. (18.08 / 20.0 Health)

>Either +50% or +100% Potion Core Resistance + Resistance V (+100%) = 0 Damage Taken. (20.0 / 20.0)

>=====

>If either one is being used it's fine but if you have both then you'll run into conflicts such as the damage reduction not working the way it's suppose to, in some cases you may take more damage if you had higher resist.

>I think that the Potion Core Resist should be it's own damage reduction attribute that isn't mixed with Vanilla Resist since currently it causes these conflicts to occur. It could go after Vanilla Resist reduces the damage so like if you took 50 damage, and had 50% vanilla resist, that lowers to 25 damage... and if you had 25% Potion Core resist... that lowers to 18.75 damage.

===========

I dunno if RLCraft has Potion Tweaker but even then there's still some sort of conflict going on when using both Vanilla Resist & Potion Core's Damage Resist. If you factor in Potion Tweaker and have it grant Resist by 10% per level instead of the default 20%... the DR doesn't add up correctly when yo go beyond Level 5. This doesn't happen if you aren't using Potion Core.

P.S. Also wonder if the HUD Element for showing your Damage Resist whenever you have Vanilla Resist or Potion Core Resist can be changed so it only shows the overlay whenever you have Potion Core's Damage Resist Attribute, and not when you have any Vanilla Resist, that is if it's possible to change the Potion Core Damage resist Attribute to be it's own damage reduction instead of being linked to Vanilla Resist.

**Comment by Meldexun** [comment]
I'm sorry, I somehow missed looking at this issue but thanks for the detailed suggestion.

Actually this is something for RLCraft and thus RLTweaker v1.12.2-0.5.6 has an option to fix the issue. But sadly the mixin from  Potion Tweaker to the EntityLivingBase class is very invasive which in fact just overrides all changes from RLTweaker. I suggest you to ask the Potion Tweaker developer to make his mixin less invasive to not override the RLTweaker changes.

**Comment by Z-Tunic** [comment]
It's alright and no problem, I gave it a test and looks like both Vanilla Resist & Potioncore Resist stack on top of each other correctly, for example...
Resist IV (80%) and Potioncore Resist (20%) will actually be 100% Resist in total, 0 damage taken.
Resist III (60%) and Potioncore Resist (40%) will actually be 100% Resist in total, 0 damage taken.

It also works fine if you happen to overflow the total resist.
Resist III (60%) and Potioncore Resist (100%) would be 160% Resist but acts as it's 100%, which makes sense since there's nothing really to gain beyond 100% Total Resist. As for the damage taken... it's still 0 where before it would've been some form of damage taken.

The calculation is fixed, though... I was hoping if Potioncore's Resist can be it's own damage reduction instead of stacking on top of the vanilla resist in general, unless that can't be done as has to be done on Potioncore's side. If it were to be it's own form of damage reduction. Rather than it stacking you'll have something like this.

...I dunno if vanilla goes first and then potioncore or if potioncore goes first and then vanilla but here's an example.

If vanilla resist goes first...
You took 50 damage, but you have 60% Vanilla Resist, that gets lowered to 20 damage but you also have 40% Potioncore Resist, so that 20 gets reduced to 12 damage.

If potioncore goes first...
You took 50 damage, but you have 40% Potioncore Resist, that gets lowered to 30 damage but you also have 60% Vanilla Resist, so that 30 gets reduced to 12 damage.

Looks like no matter the order it appears to be the same result. I prob got my math wrong, though. There's a potion that can lower your resist but I dunno if it's potioncore's or vanilla's resist.

If something reduced your Potioncore Resist... since there's a potion that can lower your resist.
You took 50 damage, but you have 60% Vanilla Resist, that gets lowered to 20 damage but you also have -50% Potioncore Resist, so that 20 gets increased to 30 damage.

If you already had some Potioncore Resist and something lowered it...
You took 50 damage, but you have 60% Vanilla Resist, that gets lowered to 20 damage but you also have 70% Potioncore Resist, however there's also -50% Potioncore Resist due to the potion, leading to only 20% Potioncore Resist. That 20 gets lowered to just 16 damage.

If it still stacked like it currently does...
You took 50 damage. You have 60% Vanilla Resist but you also have -50% Potioncore Resist, your total resist is 10% so the damage taken would be 45.

---

Again, I prob got my math wrong with this, but with so many modded reductions added from other mods, they don't all stack together but run their reductions prob related to their event, priority or modid. This is only a guess, though.

One thing to mention, if Potioncore Resist does become it's own damage reduction, the potion "Potion of Vulnerability" would prob need to be looked at so it affects Potioncore's Resist instead of affecting Vanilla Resist.

This was quite a write-up, so hopefully I explained it well.

**Comment by Meldexun** [comment]
I just reworked the resistance calculation again with 1.12.2-0.5.8. Now it works like a normal attribute with config options that let you configure the value to your liking.

Explanation of alternativeResistanceMode (because I forgot to add the description):
If you have two modifiers with amount=0.3 and operation=2 then this is the difference:
Normal Mode: `1 - ((1.0 * (1.0 + 0.3) * (1.0 * 0.3)) - 1) = 0.31` which means you get 69% less damage.
Alternative Mode: `1 - (1.0 * (1.0 - 0.3) * (1.0 - 0.3)) = 0.51` which means you get 49% less damage.
