### ISSUE TITLE
[1.12.2] Damage Reduction Oddity & Resist Border Hud Oddity

### ISSUE THREAD

**Issue by Z-Tunic** [Meldexun/RLTweaker#5]
Before I get into the details, thank you for the recent resist config as this allowed Potioncore's Damage Resist to be it's own damage reduction. I've done some exploring with the calculation and I have some findings.

Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 5
Baubles-1.12-1.5.2
HadEnoughItems_1.12.2-4.24.1
PotionCore-1.9_for_1.12.2
QualityTools-1.0.7_for_1.12.2
RLTweaker-1.12.2-0.5.8

---

Before I begin, this is my current config from a fresh regen, no changes were made during this test.
![image](https://user-images.githubusercontent.com/36653806/222937096-d19cfe1c-c66c-4db3-a6b2-71346fae235a.png)

Alright, this is a strange one when you have the config regen. For some reason, the Red Resist Border will render fine when you have either Vanilla Resist or Potioncore Resist... though the damage reduction get a bit iffy. "Alternative Resistance Mode" is TRUE by default whenever the config is regen'd.

> 1 Damage Taken
60% Vanilla Resist = 0.4
50% Potioncore Resist = 0.5
60% Vanilla Resist & 50% Potioncore Resist = 0.24
Red Resist Border renders

That looks kinda off with 60% Vanilla & 50% Potioncore being 0.24 damage, though here's the odd part when I reload minecraft while the config file was made, no changes were made at all.

> 1 Damage Taken
60% Vanilla Resist = 0.4
50% Potioncore Resist = 0.5
60% Vanilla Resist & 50% Potioncore Resist = 0.2
Red Resist Border does NOT render.

Now I'm gonna change the "Alternative Resistance Mode" to FALSE, which I think is letting the Potioncore Resist stack on top of the vanilla resist.

> 1 Damage Taken
60% Vanilla Resist = 0.4
40% Potioncore Resist = 0.6
60% Vanilla Resist & 40% Potioncore Resist = 0
Red Resist Border renders.

That's looks to be correct, stacks as it should and the Red Resist Border renders. Not sure why the damage reduction is a bit off from a fresh config regen and the Red Resist Border not working if "Alternative Resistance Mode" set to TRUE. The Border gets weird if you have your resist lowered and there's a possible oddity with the damage calculation if it isn't reaching 100%.

"Alternative Resistance Mode" is set to FALSE

> 1 Damage Taken
40% Vanilla Resist = 0.6
40% Potioncore Resist = 0.6
-50% Vulnerability = 1.5
-50% Potioncore Resist = 1.5
-50% Vulnerability & 50% Potioncore Resist = 1.75
40% Vanilla Resist & 40% Potioncore Resist = 0.04
40% Vanilla Resist & -50% Vulnerability = 1.3
40% Potioncore Resist & -50% Vulnerability = 1.3
40% Vanilla Resist & 40% Potioncore Resist & -50% Vulnerability = 1.02
40% Vanilla Resist & -50% Potioncore Resist = 1.3
40% Potioncore & -50% Potioncore Resist = 1.3
40% Vanilla Resist & 40% Potioncore Resist & -50% Potioncore Resist = 1.02
40% Vanilla Resist & 40% Potioncore Resist & -50% Vulnerability & -50% Potioncore Resist = 1.51

I dunno if that's correct, also if you have any of the Red Border Resist Rendering and your resist is lowered... it won't render.

Also... checking this out.
80% Potioncore Resist = 0.2
80% Potioncore Resist & -50% Vulnerability = 1.1
80% Potioncore Resist & -50% Potioncore Resist = 1.1
80% Potioncore Resist & -50% Vulnerability & -50% Potioncore Resist = 1.55

---

"Alternative Resistance Mode" is set to TRUE

> 1 Damage Taken
40% Vanilla Resist = 0.6
40% Potioncore Resist = 0.6
-50% Vulnerability = 1.5
-50% Potioncore Resist = 1.5
-50% Vulnerability & 50% Potioncore Resist = 2.25
40% Vanilla Resist & 40% Potioncore Resist = 0.36
40% Vanilla Resist & -50% Vulnerability = 0.9
40% Potioncore Resist & -50% Vulnerability = 0.9
40% Vanilla Resist & 40% Potioncore Resist & -50% Vulnerability = 0.54
40% Vanilla Resist & -50% Potioncore Resist = 0.9
40% Potioncore & -50% Potioncore Resist = 0.9
40% Vanilla Resist & 40% Potioncore Resist & -50% Potioncore Resist = 0.54
40% Vanilla Resist & 40% Potioncore Resist & -50% Vulnerability & -50% Potioncore Resist = 0.81

Red Resist Border only rendered when I had negative resist from either Vulnerability or the Attribute itself, which stacks on top of each other.

Also... this one seems to be correct, prob due to the way it goes.
80% Potioncore Resist = 0.2
80% Potioncore Resist & -50% Vulnerability = 0.3
80% Potioncore Resist & -50% Potioncore Resist = 0.3
80% Potioncore Resist & -50% Vulnerability & -50% Potioncore Resist = 0.45

At first I thought it would take away from your Potioncore Resist and then amp the damage, aka 80 - 50 becoming 30% Potioncore resist but it actually uses the postive value first, then the negative values... separately. Vulnerability I figure would change the damage after everything has gone through much like with the Pain Potion from Extra Alchemy, which amps the damage taken after all calculations were done, if I remember.

The positive goes first, then the negative... and then the negative, which... actually is correct in a way if you wanted to to do that.
1 becomes 0.2 (+80%), 0.2 becomes 0.3(-50%), and finally... 0.3 becomes 0.45(-50%).

---

That was quite a write-up with checking out the damage calculations, though for the Red Resist Border, I do have an idea with it rendering.

"Alternative Resistance Mode" if TRUE
Red Resist Border will render for only the Potioncore Resist, since it's technically it's own reduction. I would say that negative potioncore resist should take away from the hud but it has it's own damage calculation, so I figure maybe it shouldn't affect it. Vulnerability is also it's own thing so it shouldn't affect it either.

"Alternative Resistance Mode" if FALSE
Red Resist Border will show for both Vanilla Resist & Potioncore Resist, since in a way they stack together. Unsure how Negative Potioncore Resist & Vulnerability would affect the hud but as it is currently it makes the Red Border not render if you have any negative resist.

If no resist is shown and you have negative resist from either Vulnerability or Potioncore Resist, then... nothing should happen to the hud since there's nothing there already.

...alright, I hope I have everything correct with this testing. This was definitely quite a write-up.

---

***EDIT***
I forgot to mention but seeing as Potioncore Resist is kinda it's own damage reduction if using the "Alternative Resistance Mode", I wonder if there could be an option to set caps for how high and how low you can have the Potioncore Resist be at. For example...

If Max is 0.9, then your Potioncore Resist will be capped at 90% Reduction. It can go above 90% but only 90% of it will actually be used.

If Min is -1.0, then your Potioncore Resist will be capped at -100% which is 2x the damage taken. You can go further below -100% but it'll still be treated as if it was at -100%.

Both the min & max values can be config'd if one wishes to control just how much of an impact Potioncore Resist should have. Any extras will act as a sort of buffer so like if you had 120% Resist but the cap is 90%, your actual resist is still 90% with 30% of being unused. If something lowered it by -50%... you'll be at 70% Resist.

**Comment by Z-Tunic** [comment]
Gave this another look, it looks like each attribute modifier is it's own reduction so... for example. Having two 50% Potioncore Resist wouldn't be 100% DR but rather it'll be 50%, and then another 50%. Here's an example.

"Alternative Resistance Mode" if TRUE

1 Damage
50% x1 = 0.5
50% x2 = 0.25
50% x3 = 0.125
50% x3 & -50% x1 = 0.1875
50% x3 & -50% x2 = 0.28125
50% x3 & -50% x2 = 0.28125
50% x3 & -50% x3 = 0.421875
-50% x1 = 1.5
-50% x2 = 2.25
-50% x3 = 3.375

It's still going with positives and then negatives, but as it's own setting. I don't suppose there could be a config to allow the Potioncore Resist Attribute to stack as one value. Example...

20% & 35% & -25% = 30%
20 + 35 = 55 - 25 = 30

In this example, you would have 30% Potioncore Resist after the calculation. In terms of damage... 1 damage would be 0.7 in this case instead of it being 1 to 0.8 to 0.52 and finally 0.65 with the current Resist System.

I suppose it's kinda close still, but I'm prob too used to Tinker's Evolutions' Damage Taken attribute which did this type of reduction.

**Comment by Meldexun** [comment]
Please create a new issue the next time when reporting multiple issues.

The calculations are working as intended and are fully configurable (as you have noticed already). In 1.12.2-0.5.10 I added config options to modify the attribute modifier from the vulnerable potion.

The resistance bar rendering is fixed in 1.12.2-0.5.9.
